spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  endpointUrl: http://moviefun-responsive-bongo.apps.pikes.pal.pivotal.io
  accessKey:
  secretKey:
  bucketName: moviefun

